<?xml version="1.0" encoding="utf-8"?> <!--Created by Aryan Chandra (C3360071). File Name: budget.xml Created on: 17/09/2020-->
<?xml-stylesheet href="holiday-xslt.xsl" type="text/xsl"?>

	<!DOCTYPE Holiday [
	<!ELEMENT Holiday (pack+)>
	<!ELEMENT pack (packName, desc, holidayWeb?, cost, noOfNights, popularity, accomo+, couponCode?, review*, promoPic+, picURL, datesAvail, packAvail)>
	<!ELEMENT packName (#PCDATA)> 	
	<!ELEMENT desc (#PCDATA)> 
	<!ELEMENT holidayWeb (#PCDATA)>	
	<!ELEMENT cost (#PCDATA)> 	
	<!ELEMENT noOfNights (#PCDATA)> 	
	<!ELEMENT popularity (#PCDATA)> 	
	<!ELEMENT accomo (location+, addCost?)> 
	<!ELEMENT location (#PCDATA)> 
	<!ELEMENT addCost (#PCDATA)>
	<!ELEMENT couponCode (#PCDATA)> 	
	<!ELEMENT review (reviewName*, reviewD*,reviewRating*)> 	
	<!ELEMENT reviewName (#PCDATA)>
	<!ELEMENT reviewD (#PCDATA)>
	<!ELEMENT reviewRating (#PCDATA)>
	<!ELEMENT promoPic (#PCDATA)> 	
	<!ELEMENT picURL (#PCDATA)> 	
	<!ELEMENT datesAvail (#PCDATA)> 
	<!ELEMENT packAvail (#PCDATA)>  

	<!ATTLIST pack code CDATA #IMPLIED> 
	<!ATTLIST Holiday category CDATA #IMPLIED>	
	<!ENTITY AVAIL "Available">
	<!ENTITY UNAVAI "Unavailable">
]>


<Holiday category = "Budget">
	<pack code = "35634">
		<packName>Relax in Bali</packName>
		<desc>Being such a close destination to Australia, it is one of the most toured places and for a very good reason! The place is gorgeous, the food is delicious, you just don't feel like doing anything at all, just want to relax and laze around 24/7 and that's perfectly okay! Whenever felt like, go to the amazing pool in the hotel or take a nice long walk along the beach. Proceed to explore the beautiful culure </desc>

		<holidayWeb>https://www.flightcentre.com.au/product/12973530</holidayWeb>

		<cost>$1299</cost>

		<noOfNights>7</noOfNights>

		<popularity>4/5</popularity>

		<accomo>
			<location>Bali</location>
			<addCost></addCost>
		</accomo>

		<couponCode>BALITRIP</couponCode>

		<review>
			<reviewName>Kuterukito Rukutokatakakitokuto</reviewName>
			<reviewD>This was lovely, my girlfriend and just came back and honestly this was a well needed break! One of the most relaxing times we've had in a while and couldn't have been any better, thank you!	</reviewD>
			<reviewRating>4.5/5</reviewRating>
		</review>

		<promoPic>baliTemple.jpg</promoPic>

		<picURL>images/baliTemple.jpg</picURL>

		<datesAvail>1st February - 31st August</datesAvail>

		<packAvail>&AVAIL;</packAvail>
	</pack>

	<pack code = "49683">
		<packName>Sunshine Coast</packName>
		<desc>Enjoy 5 glorious days in Australia's very own Sunshine Coast! You CANNOT miss out on the theme parks: Movie World, Dreamworld, Wet'n'Wild and Sea World. There is so much to do in all of these parks perfect for hours of fun! 5 days dedicated to each theme park, and then spend the last day relaxing on the beach, take a swin if you feel the need to and then end the day off with some shopping along the malls and eating the delicious food the place has to offer.</desc>

		<holidayWeb></holidayWeb> <!-- left out for showcare purposes -->

		<cost>$450</cost>

		<noOfNights>5</noOfNights>

		<popularity>4/5</popularity>

		<accomo>
			<location>Gold Coast</location>
			<addCost></addCost>
		</accomo>

		<couponCode>SUNSHINE20</couponCode>

		<review>
			<reviewName>Peepo Champ</reviewName>
			<reviewD>Took myself and my family up from Sydney for the 5 day and we were not disappointed at all! The kids, my wife and myself all LOVED, and we cannot express this enough, LOVED the theme parks. I think we all decided on Movie world being the best hahahaha, but it was great!</reviewD>
			<reviewRating>5/5</reviewRating>
		</review>

		<promoPic>goldcoast.jpg</promoPic>

		<picURL>images/goldcoast.jpg</picURL>

		<datesAvail>20th January - 31st August</datesAvail>

		<packAvail>&AVAIL;</packAvail>
	</pack>

	<pack code = "40896">
		<packName>Glaciers are Kinda Cool</packName>
		<desc>New Zealand, there is nothing more pretty than the green grass here and the huge mountains with snow on top, it's just so relaxing and nice to look at. Why miss out?! For 4 nights stay in Queenstown and discover what the South Island has to offer. Take a drive and visit the Glaciers in Te Waipounamu, trust us, once you get a look at the view you will fall in love instantly.</desc>

		<holidayWeb>https://www.flightcentre.com.au/product/13148601</holidayWeb>

		<cost>$1300</cost>

		<noOfNights>5</noOfNights>

		<popularity>4/5</popularity>

		<accomo>
			<location>New Zealand</location>
			<addCost></addCost>
		</accomo>

		<couponCode></couponCode>

		<review>
			<reviewName>Samuel Pog</reviewName>
			<reviewD>My mates and I took this trip a week ago and honestly it was great man, we just checked out the glaciers and everything and it was amazing. Sick trip, highly recommend it :))</reviewD>
			<reviewRating>5/5</reviewRating>
		</review>

		<promoPic>nzglacier.jpg</promoPic>

		<picURL>images/nzglacier.jpg</picURL>

		<datesAvail>1st June - 1st September</datesAvail>

		<packAvail>&AVAIL;</packAvail>
	</pack>
</Holiday>