<?xml version="1.0" encoding="utf-8"?> <!--Created by Aryan Chandra (C3360071). File Name: template.xml Created on: 17/09/2020-->
<?xml-stylesheet href="holiday-xslt.xsl" type="text/xsl"?>

	<!DOCTYPE Holiday [
	<!ELEMENT Holiday (pack+)>
	<!ELEMENT pack (packName, desc, holidayWeb?, cost, noOfNights, popularity, accomo+, couponCode?, review*, promoPic+, picURL, datesAvail, packAvail)>
	<!ELEMENT packName (#PCDATA)> 	<!--simply the name of the package-->
	<!ELEMENT desc (#PCDATA)>	<!--description of the package-->
	<!ELEMENT holidayWeb (#PCDATA)> <!--website leading to holiday-->
	<!ELEMENT cost (#PCDATA)> 	<!--cost of the package-->
	<!ELEMENT noOfNights (#PCDATA)> 	<!--number of nights the package goes for-->
	<!ELEMENT popularity (#PCDATA)> 	<!--stars out of five-->
	<!ELEMENT accomo (location+, addCost?)> 	<!--where the accomodation is and any other additional costs-->
	<!ELEMENT location (#PCDATA)> 
	<!ELEMENT addCost (#PCDATA)>
	<!ELEMENT couponCode (#PCDATA)> 	<!--coupon code-->
	<!ELEMENT review (reviewName*, reviewD*,reviewRating*)> 	<!--a review of the package-->
	<!ELEMENT reviewName (#PCDATA)>
	<!ELEMENT reviewD (#PCDATA)>
	<!ELEMENT reviewRating (#PCDATA)>
	<!ELEMENT promoPic (#PCDATA)> 	<!--name of photo being promoted-->
	<!ELEMENT picURL (#PCDATA)> 	<!--URL of photo being promoted-->
	<!ELEMENT datesAvail (#PCDATA)> <!--the dates that the pack is available from-->
	<!ELEMENT packAvail (#PCDATA)>  <!--Unavailable/available status for the pack-->

	<!ATTLIST pack code CDATA #IMPLIED> 	<!--code of the pack-->
	<!ATTLIST Holiday category CDATA #IMPLIED> <!--Category of the pack-->
	<!ENTITY AVAIL "Available">
	<!ENTITY UNAVAI "Unavailable">
]>

<Holiday category = "">
	<pack code = "">
		<packName></packName>
		<desc></desc>

		<holidayWeb></holidayWeb>

		<cost></cost>

		<noOfNights></noOfNights>

		<popularity></popularity>

		<accomo>
			<location></location>
			<addCost></addCost>
		</accomo>

		<couponCode></couponCode>

		<review>
			<reviewName></reviewName>
			<reviewD></reviewD>
			<reviewRating></reviewRating>
		</review>

		<promoPic></promoPic>

		<picURL></picURL>

		<datesAvail></datesAvail>

		<packAvail></packAvail>
	</pack>
</Holiday>